function [fitresult, gof] = create_FirstOrderPoly_RE_Fit_JENBACHER_JMS412GS_50Hz(input_data, RE_output_data)
%CREATEFIT(INPUT_DATA,RE_OUTPUT_DATA)
%  Create a fit.
%
%  Data for 'JENBACHER_JMS412GS_50Hz_RE_Fit' fit:
%      X Input : input_data
%      Y Output: RE_output_data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Jun-2020 14:02:39


%% Fit: 'JENBACHER_JMS412GS_50Hz_RE_Fit'.
[xData, yData] = prepareCurveData( input_data, RE_output_data );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'JENBACHER_JMS412GS_50Hz_RE_Fit' );
h = plot( fitresult, xData, yData );
legend( h, 'RE_output_data vs. input_data', 'JENBACHER_JMS412GS_50Hz_RE_Fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'input_data', 'Interpreter', 'none' );
ylabel( 'RE_output_data', 'Interpreter', 'none' );
grid on


